---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
 - 00-lso-label-nodes.yaml
 - 01-master-create-lvs-for-lso.yaml
 - 02-lso-localvolume-lvs.yaml
 - 03-lso-filesystemclass-default.yaml
