---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  telco-gitops/ran-cu: telco-gitops

bases:
  # Common Telco Optimizations
  - ../../base/configs/telco-optimized
  # Enable SCTP
  - ../../base/configs/sctp
  # SRIOV
  - ../../base/operators/openshift-sriov-network-operator
  # PAO
  - ../../base/operators/openshift-performance-addon-operator
  # OpenShift Virtualization (if using VNFs)
  # - ../../base/operators/openshift-virtualization
