apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-local-storage
  namespace: openshift-local-storage
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  targetNamespaces:
    - openshift-local-storage

