apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-local-storage-operator
  namespace: openshift-local-storage
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  channel: "4.10"
  installPlanApproval: Automatic
  name: local-storage-operator
  # Modify source name of the catalogsource for isolated network deployments
  source: redhat-operators
  sourceNamespace: openshift-marketplace

