apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: sriov-network-operators
  namespace: openshift-sriov-network-operator
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  targetNamespaces:
  - openshift-sriov-network-operator
