---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  telco-gitops/oss-bss: telco-gitops

bases:
  # Telco Optimizations
  - ../../base/configs/telco-optimized
  # OpenShift ServiceMesh
  - ../../base/operators/openshift-service-mesh
  # PAO
  # - ../../base/operators/openshift-performance-addon-operator
