---
apiVersion: v1
kind: Pod
metadata:
  # annotations: 
  #   cpu-load-balancing.crio.io: "disable"
  #   irq-load-balancing.crio.io: "disable" 
  name: qos-pod
  namespace: default
spec:
  # runtimeClassName: performance-myprofile
  # nodeSelector:
  #   kubernetes.io/hostname: worker-01
  containers:
  - name: simple-pod
    image: registry.access.redhat.com/ubi8/ubi
    resources:
      requests:
        memory: "16M"
        cpu: "1"
      limits:
        memory: "16M"
        cpu: "1"
    command:
    - /bin/bash
    - -c
    - sleep infinity
  #   volumeMounts:
  #   - mountPath: /foo
  #     name: foo-vol
  # volumes:
  #   - name: foo-vol
  #     configMap:
  #       name: cm-test
