---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  telco-gitops/combined-ran-4.6: telco-gitops

bases:
  # RWN
  - ../rwn
  # Enable SCTP
  - ../../base/configs/sctp
  # SRIOV
  - ../../base/operators/openshift-sriov-network-operator
  # PAO
  - ../../base/operators/openshift-performance-addon-operator/pao-4.8
  # PTP
  - ../../base/operators/openshift-ptp/ptp-4.8
  # Intel vRAN Acceleration Operators
  - ../../base/operators/vran-acceleration-operators

resources:
  - 01-max-pods-500.yaml
  - 02-mcp-ran-cu.yaml
  - 02-mcp-ran-du.yaml
  - 50-ran-du-disable-chronyd.yaml
  # TODO: replace by ks8 job
  - 01-mcp.yaml

patches:
# TODO: replace by k8s job
- 01-patch-mcp-master.yaml
- 03-patch-sriov-operator.yaml
