---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  telco-gitops/mgmt: telco-gitops

bases:
  #####################################################
  # Operators for MGMT Clusters
  #####################################################
  # OpenShift GitOps
  - ../../base/operators/openshift-gitops
  # Assisted Installer
  - ../../base/operators/assisted-installer
  # Red Hat Advanced Cluster Manager for Kubernetes
  # - ../../base/operators/advanced-cluster-management
  # OpenShift Container storage
  # - ../../base/operators/openshift-container-storage
  # Quay Enterprise
  # - ../../base/operators/quay-enterprise-operator
  # OpenShift Logging
  # - ../../base/operators/openshift-logging
