---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  telco-gitops/core-5g: telco-gitops

# NOTE: This node definition

bases:
  # Enable SCTP
  - ../../base/configs/sctp
  # Telco Optimizations
  - ../../base/configs/telco-optimized
  # SRIOV
  - ../../base/operators/openshift-sriov-network-operator
  # PAO
  - ../../base/operators/openshift-performance-addon-operator