apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-nmstate-operator-subscription
  namespace: openshift-nmstate 
  annotations:
    argocd.argoproj.io/sync-wave: "20"  
spec:
  channel: "4.8" 
  name: kubernetes-nmstate-operator
  source: redhat-operators 
  sourceNamespace: openshift-marketplace
