apiVersion: nmstate.io/v1beta1
kind: NMState
metadata:
  name: nmstate
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-wave: "30"
spec:
  nodeSelector:
    beta.kubernetes.io/arch: amd64
