---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    openshift.io/cluster-monitoring: "true"
  name: net-toolbox
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: net-toolbox-daemon
  namespace: net-toolbox
---
# PRIVILEGED USER
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: net-toolbox-daemon
  namespace: net-toolbox
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: net-toolbox-daemon
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: net-toolbox-daemon
subjects:
- kind: ServiceAccount
  name: net-toolbox-daemon
  namespace: net-toolbox