apiVersion: v1
data:
  htpasswd: dGVsY29hZG1pbjokMnkkMDUkVDQ5ZVFER0lpVDg5b3A2MVNlbVNDLjcwSmNlNGtpZmNnTVppTVlVbUlDZXd2M3h5Llk5b2UKb3BlcmF0aW9uczokMnkkMDUkdlhPYUwyOFNaNkFIejBDVmxzZmZkZU9aUi9jMlhNbGw3a1RoSXRUazZ3OTNSUzV2R3ZDREMKdmVuZG9yY25mMTokMnkkMDUkRGdYVVI4bnFYVUJneW51U2xpLldPTzZVcmZLOGVVNTlQRW83cEE1S25GUmY2b0JLbHRXR3EKdmVuZG9yY25mMjokMnkkMDUkaVouR2RBbkRrTmY4OHQuRDBnSEVmLnJORkxLZnFBRllxSm5PYmpZUnVSYlV1ZFZRaTBDd3EKdmVuZG9yY25mMzokMnkkMDUkbnNmS3BYaFcvWkF4em5pV3Y1bkZELnNkbXREaS53YkRzYkpLaHFHbXZrNEdUaTc3WEE0LlMK 
kind: Secret
metadata:
  creationTimestamp: null
  name: idp-htpass-secret
  namespace: openshift-config
